# .github/workflows/run_job_scraper.yml
name: Run Job Scraper

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.3'  # Adjust if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Remove if not needed

    - name: Run job scraper
      run: |
        python golangprojects.com.py | xargs -n1 -I{} python find_jobs.py {}

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Add and Commit output
      run: |
        git add docs/jobs/.
        git commit -m "Update jobs.json" || echo "No changes to commit" # handle no changes scenario

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}